version: "3.6"

secrets:
  cloudflare-token:
    file: "./secrets/cloudflare-token.secret"
  cloudflare-email:
    file: "./secrets/cloudflare-email.secret"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    command:
      - "--log.level=DEBUG"
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --api.dashboard=false
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesResolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesResolvers.letsencrypt.acme.dnschallenge.delayBeforeCheck=20
      - --certificatesresolvers.letsencrypt.acme.email=<>
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --entrypoints.websecure.http.tls.domains[0].main=dev.moabukar.co.uk
      - --entrypoints.websecure.http.tls.domains[0].sans=*.dev.moabukar.co.uk
    secrets:
      - "cloudflare-token"
      - "cloudflare-email"
    environment:
      - "CF_DNS_API_TOKEN_FILE=/run/secrets/cloudflare-token"
      - "CF_API_EMAIL_FILE=/run/secrets/cloudflare-email"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/letsencrypt

  site:
    container_name: site
    image: moabukar/mosite:28f8151
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.site.rule=Host(`site.dev.moabukar.co.uk`)' # unique router name
      - "traefik.http.routers.site.entrypoints=websecure"

  subnet-calc:
    container_name: subnet-calc
    image: moabukar/subnet-calc:b33ba69
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.subnet-calc.rule=Host(`subnet.dev.moabukar.co.uk`)' # unique router name
      - "traefik.http.routers.subnet-calc.entrypoints=websecure"

  paste-bin:
    container_name: paste-bin
    image: ghcr.io/enchant97/hasty-paste:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.paste-bin.rule=Host(`paste.dev.moabukar.co.uk`)' # unique router name
      - "traefik.http.routers.paste-bin.entrypoints=websecure"




