# traefik.yml

global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

certificatesResolvers:
  letsencrypt:
    acme:
      email: <>
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
        - "1.1.1.1:53"
        - "1.0.0.1:53"
        delayBeforeCheck: "20"

providers:
  file:
    filename: /Users/mohameda/Documents/learning/traefik-dns/traefik-confs/dynamic-conf.yml
    watch: true

  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
